### ISSUE TITLE
Landscape scenario does not show up

### ISSUE THREAD

**Issue by bowie2211** [Microsoft/AutonomousDrivingCookbook#36] opened 2018-04-24 04:25 UTC
## Problem description
Starting AirSim via the provided script AD_Cookbook_Start_AirSim.ps1 with landscape as scenrio ends in a black and white screen.
Starting the other scenrios works fine

## Exepriment/Environment details
* Tutorial used: AirSimE2EDeepLearning
* Environment used: landscape

**Comment by mitchellspryn** [comment] 2018-04-24 05:50
Can you give me the command line that you are using to start it? I just tried running

`
> .\AD_Cookbook_Start_AirSim.ps1 landscape
`

from a powershell window, and everything appears OK.

**Comment by bowie2211** [comment] 2018-04-26 03:26
I have tried to start it from an Power Shell Integrated Console in Visual Code.
Starting with parameter city or coastline works perfectly.
It is only the landscape that makes problems.
I will check out to start it from a Power Shell window outside Visual Code.

**Comment by mitchellspryn** [comment] 2018-04-26 05:24
Intenteresting. Can you also see what happens if you try neighborhood from the Integrated Console?

**Comment by bowie2211** [comment] 2018-04-28 18:07
Neighborhood also is not working.

Could you please give some information how I can run the official AirSim binaries?

**Comment by mitchellspryn** [comment] 2018-04-28 19:59
[Here](https://github.com/Microsoft/AirSim/blob/master/docs/use_precompiled.md). Although, we haven't tested the official binaries with our code, so they're not guaranteed to work. 

What are the specs of the system you are trying to run on?

**Comment by mitchellspryn** [comment] 2018-06-14 05:28
There is no action from us on this issue. Can't reproduce. Closing.

**Closed** 2018-06-14 05:28 UTC
