### ISSUE TITLE
AirSim in headless mode

### ISSUE THREAD

**Issue by pienrojp** [Microsoft/AutonomousDrivingCookbook#34] opened 2018-04-20 21:42 UTC
Are there anyway I can just run my model with AirSim on a command line in Linux terminal ? (In other word, headless mode) So that I can train them on my lab server.

Thank you!

**Comment by mitchellspryn** [comment] 2018-04-21 04:55
The binaries that we provide are windows only. This is a duplicate of [this issue](https://github.com/Microsoft/AutonomousDrivingCookbook/issues/8). 

You may experiment with [building AirSim from source](https://github.com/Microsoft/AirSim/blob/master/docs/build_linux.md).

**Closed by mitchellspryn** 2018-04-21 04:55 UTC
